-- Core editor mappings. Plugin mappings live next to their setup in plugin/.

vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<cr>", { desc = "Clear search highlight" })
vim.keymap.set("n", "<leader>v", "ggVG", { desc = "Select whole buffer" })
vim.keymap.set("v", "p", '"_dP`[v`]=', { desc = "Paste without yank" })
vim.keymap.set("n", "J", "mzJ`z", { desc = "Better join" })
vim.keymap.set("n", "i", function()
    return vim.fn.getline("."):len() == 0 and '"_cc' or "i"
end, { desc = "Auto-indent on empty line", expr = true })
vim.keymap.set("n", "j", "gj", { desc = "Navigate wrapped lines" })
vim.keymap.set("n", "k", "gk", { desc = "Navigate wrapped lines" })
vim.keymap.set("v", "<", "<gv", { desc = "Indent left" })
vim.keymap.set("v", ">", ">gv", { desc = "Indent right" })
vim.keymap.set("n", "<C-d>", "<C-d>zz", { desc = "Half page down (centred)" })
vim.keymap.set("n", "<C-u>", "<C-u>zz", { desc = "Half page up (centred)" })
vim.keymap.set("n", "n", "nzzzv", { desc = "Next search result (centred)" })
vim.keymap.set("n", "N", "Nzzzv", { desc = "Prev search result (centred)" })
vim.keymap.set("n", "<C-h>", "<C-w>h", { desc = "Focus left window" })
vim.keymap.set("n", "<C-j>", "<C-w>j", { desc = "Focus lower window" })
vim.keymap.set("n", "<C-k>", "<C-w>k", { desc = "Focus upper window" })
vim.keymap.set("n", "<C-l>", "<C-w>l", { desc = "Focus right window" })
vim.keymap.set("n", "<C-Up>", "<cmd>resize +2<cr>", { desc = "Increase height" })
vim.keymap.set("n", "<C-Down>", "<cmd>resize -2<cr>", { desc = "Decrease height" })
vim.keymap.set("n", "<C-Left>", "<cmd>vertical resize -2<cr>", { desc = "Decrease width" })
vim.keymap.set("n", "<C-Right>", "<cmd>vertical resize +2<cr>", { desc = "Increase width" })
vim.keymap.set("n", "<leader>wd", "<C-W>c", { desc = "Delete window" })
vim.keymap.set("n", "<leader>w-", "<C-W>s", { desc = "Split below" })
vim.keymap.set("n", "<leader>w|", "<C-W>v", { desc = "Split right" })
vim.keymap.set("n", "<leader>w=", "<C-w>=", { desc = "Equalise windows" })
vim.keymap.set("n", "<leader>fn", "<cmd>enew<cr>", { desc = "New file" })
vim.keymap.set("n", "<leader>ca", vim.lsp.buf.code_action, { desc = "Code action" })
vim.keymap.set("n", "<leader>cr", vim.lsp.buf.rename, { desc = "Rename symbol" })
vim.keymap.set("n", "<leader>co", function()
    vim.lsp.buf.code_action({
        context = { only = { "source.organizeImports" }, diagnostics = {} },
        apply = true,
    })
end, { desc = "Organise imports" })
vim.keymap.set("n", "<leader>cq", function()
    vim.lsp.buf.code_action({
        context = { only = { "quickfix" }, diagnostics = {} },
        apply = true,
    })
end, { desc = "Quick fix" })
vim.keymap.set("n", "<leader>cl", vim.lsp.codelens.run, { desc = "Run code lens" })
vim.keymap.set("i", "<C-k>", vim.lsp.buf.signature_help, { desc = "Signature help" })
vim.keymap.set("n", "<leader>cd", vim.diagnostic.open_float, { desc = "Line diagnostics" })
vim.keymap.set("n", "[d", function()
    vim.diagnostic.jump({ count = -1, float = true })
end, { desc = "Prev diagnostic" })
vim.keymap.set("n", "]d", function()
    vim.diagnostic.jump({ count = 1, float = true })
end, { desc = "Next diagnostic" })
vim.keymap.set("n", "[q", "<cmd>cprev<cr>", { desc = "Prev quickfix" })
vim.keymap.set("n", "]q", "<cmd>cnext<cr>", { desc = "Next quickfix" })
vim.keymap.set("t", "<Esc><Esc>", "<C-\\><C-n>", { desc = "Exit terminal mode" })

vim.keymap.set("n", "<leader>uh", function()
    local buf = vim.api.nvim_get_current_buf()
    vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled({ bufnr = buf }), { bufnr = buf })
end, { desc = "Toggle inlay hints" })
