vim.pack.add({ "https://github.com/monaqa/dial.nvim" })

require("config.dial")

vim.keymap.set("n", "<C-a>", function()
    return require("dial.map").inc_normal()
end, { desc = "Increment", expr = true })
vim.keymap.set("n", "<C-x>", function()
    return require("dial.map").dec_normal()
end, { desc = "Decrement", expr = true })
vim.keymap.set("v", "<C-a>", function()
    return require("dial.map").inc_visual()
end, { desc = "Increment", expr = true })
vim.keymap.set("v", "<C-x>", function()
    return require("dial.map").dec_visual()
end, { desc = "Decrement", expr = true })
