add_newline = false

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$package\
$character
"""
right_format = "$cmd_duration$jobs$sudo"

[character]
error_symbol = "[](bold red)"
vimcmd_symbol ="[](bold green)"
