%YAML 1.1
---
git:
  diffRenderers:
  - colorArg: always
    command: delta --paging=never
  overrideGpg: true
gui:
  border: single
  nerdFontsVersion: '3'
  showFileTree: true
  showRandomTip: false
