# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
    config,
    lib,
    pkgs,
    modulesPath,
    ...
}:

{
    imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot.initrd.availableKernelModules = [
        "xhci_pci"
        "thunderbolt"
        "nvme"
        "uas"
        "usb_storage"
        "sd_mod"
    ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-intel" ];
    boot.extraModulePackages = [ ];

    fileSystems."/" = {
        device = "/dev/disk/by-uuid/d8191e1a-7791-488b-8a7a-77dddee1b7e1";
        fsType = "btrfs";
    };

    fileSystems."/home" = {
        device = "/dev/disk/by-uuid/d8191e1a-7791-488b-8a7a-77dddee1b7e1";
        fsType = "btrfs";
        options = [ "subvol=home" ];
    };

    fileSystems."/nix" = {
        device = "/dev/disk/by-uuid/d8191e1a-7791-488b-8a7a-77dddee1b7e1";
        fsType = "btrfs";
        options = [ "subvol=nix" ];
    };

    fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/93F9-01EF";
        fsType = "vfat";
        options = [
            "fmask=0077"
            "dmask=0077"
        ];
    };

    swapDevices = [ ];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
