# DO-NOT-EDIT. This file was auto-generated by omarchy-import.
# Use `nix run .#write-flake` to regenerate flake.nix after it changes.
{ inputs, ... }:
{
  flake-file.inputs = {
    plugins-mars-nvim = {
      url = "github:steve-lohmeyer/mars.nvim";
      flake = false;
    };
  };

  flake.modules.nixvim.nvim =
    { pkgs, ... }:
    {
      extraPlugins = [
        (pkgs.vimUtils.buildVimPlugin {
          name = "mars-nvim";
          src = inputs.plugins-mars-nvim;
        })
      ];
    };
}
