-- DO-NOT-EDIT. This file was auto-generated by omarchy-import.

return {
    ["Mars"] = {
        nvim = "plugin",
        scheme = "mars",
        source = "https://github.com/steve-lohmeyer/omarchy-mars-theme",
    },
}
