[include]
files = [
    "animation.toml",
    "appearance.toml",
    "events.toml",
    "general.toml",
    "input.toml",
    "keybinds.toml",
    "layer-rule.toml",
    "layout.toml",
    "output.toml",
    "window-rule.toml",
    "workspace.toml",
]

[include.optional]
files = [
    "~/.config/umbriel/noctalia.toml",
]
