[include]
files = [
    "audio.toml",
    "bar.toml",
    "brightness.toml",
    "control-center.toml",
    "dock.toml",
    "hooks.toml",
    "idle.toml",
    "keybinds.toml",
    "location.toml",
    "lockscreen.toml",
    "notification.toml",
    "osd.toml",
    "plugins.toml",
    "shell.toml",
    "theme.toml",
    "wallpaper.toml",
    "widget.toml",
]
