[theme.templates]
builtin_ids = ["btop", "foot", "gtk3", "gtk4", "kcolorscheme", "qt", "umbriel"]
community_ids = ["claude-code", "discord", "gimp", "libreoffice", "papirus-icons", "prismlauncher", "steam", "zellij", "bat", "fzf", "lazygit", "yazi"]

[theme.templates.user.konsole]
input_path = "~/.config/noctalia/templates/konsole.colorscheme"
output_path = "~/.local/share/konsole/Noctalia.colorscheme"

[theme.templates.user.nvim]
input_path = "~/.config/noctalia/templates/nvim.lua"
output_path = "~/.config/nvim/noctalia.lua"
post_hook = "pkill -SIGUSR1 nvim"

[theme.templates.user.qutebrowser]
input_path = "~/.config/noctalia/templates/qutebrowser.py"
output_path = "~/.config/qutebrowser/noctalia/colors.py"
post_hook = "~/.local/bin/noctalia-qutebrowser-reload"

[theme.templates.user.selector]
input_path = "~/.config/noctalia/templates/selector.toml"
output_path = "~/.config/selector/noctalia.toml"
post_hook = "systemctl --user try-restart selector.service"
