name: check

on:
  push:
    branches: [master]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            extra-substituters = https://nix-community.cachix.org https://noctalia.cachix.org
            extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= noctalia.cachix.org-1:pCOR47nnMEo5thcxNDtzWpOxNFQsBRglJzxWPp3dkU4=

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - run: nix flake check --no-build -L

      - name: build non-host checks
        run: |
          nix build -L --no-link $(nix eval --raw .#checks.x86_64-linux --apply \
            'cs: builtins.concatStringsSep " " (map (n: ".#checks.x86_64-linux." + n)
              (builtins.filter (n: builtins.substring 0 5 n != "host-") (builtins.attrNames cs)))')
